apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: multiarch-manifest-create
spec:
  description: >-
    Create a Multi-Architecture manifest for the given images and push the manifest to the given registry.
  params:
    - name: imagename
      description: Name of the multiarch image to create
    - name: architectures
      description: Array of architectures to build
      type: array
  steps:
    - name: create-manifest
      securityContext:
        capabilities:
          add:
            - SETFCAP
      image: registry.access.redhat.com/ubi9/buildah:9.3-12
      args:
        - "$(params.architectures[*])"
      env:
        - name: PARAM_MULTIARCH_IMAGE
          value: "$(params.imagename)"
      script: |
        #!/bin/bash -x

        set -euf -o pipefail

        echo "Number of source images: $#"
        echo "Architectures: $*"
        echo "Destination: ${PARAM_MULTIARCH_IMAGE}"

        buildah --storage-driver=overlay manifest create "${PARAM_MULTIARCH_IMAGE}"

        for arch in "${@}"; do
          buildah manifest add "${PARAM_MULTIARCH_IMAGE}" "${PARAM_MULTIARCH_IMAGE}-${arch}"
        done

        buildah manifest push "${PARAM_MULTIARCH_IMAGE}"
