kind: TaskRun
apiVersion: tekton.dev/v1
metadata:
  name: multiarch-manifest-create
spec:
  taskRef:
    name: multiarch-manifest-create
  params:
    - name: architectures
      value:
        - x86
        - arm
    - name: imagename
      value: quay.io/tosmi/example-container:v1.0
