apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: multiarch-manifest-create
spec:
  description: >-
    Create a Multi-Architecture manifest for the given images and push the manifest to the given registry.
  params:
    - name: images
      description: Array of images to be includes in the multiarchtitecture manifest
      type: array
    - name: multiarch-image
      description: Name of the multiarch image to create
  steps:
    - name: create-manifest
      securityContext:
        capabilities:
          add:
            - SETFCAP
      image: registry.access.redhat.com/ubi9/buildah:9.3-12
      args:
        - "$(params.images[*])"
      env:
        - name: PARAM_MULTIARCH_IMAGE
          value: $(params.multiarch-image)
      script: |
        #!/bin/bash -x

        set -euf -o pipefail

        echo "Number of source images: $#"
        echo "Source images: $*"
        echo "Destination: ${PARAM_MULTIARCH_IMAGE}"

        buildah --storage-driver=overlay manifest create "${PARAM_MULTIARCH_IMAGE}"

        for image in "${@}"; do
          buildah manifest add "${PARAM_MULTIARCH_IMAGE}" "${image}"
        done

        buildah manifest push "${PARAM_MULTIARCH_IMAGE}"
