---
apiVersion: v1
kind: Namespace
metadata:
  name: pod-startup-debug
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: theclaim
  namespace: pod-startup-debug
spec:
  storageClassName: "gp2-csi"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-many-files
  namespace: pod-startup-debug
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/ubi9/ubi:latest
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash

              for n in {1..100000}; do
                touch /data/file.$n
              done

          volumeMounts:
          - mountPath: /data
            name: pvc
          imagePullPolicy: Always
          name: create-many-files
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: theclaim
