---
apiVersion: v1
kind: Namespace
metadata:
  name: pod-startup-debug
---
apiVersion: v1
kind: Pod
metadata:
  name: test-startup
  namespace: pod-startup-debug
spec:
  containers:
  - name: test-startup
    image: registry.redhat.io/ubi9/ubi:latest
    command:
    - /bin/sleep
    - infinity
    volumeMounts:
    - mountPath: /data
      name: pvc
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: theclaim
