---
- name: "Create activation key RHEL 8"
  theforeman.foreman.activation_key:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite.url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "RHEL 8"
    lifecycle_environment: "Lab"
    content_view: "CCV: RHEL 8"
    subscriptions:
      - pool_id: "{{ satellite.pool_id }}"
    content_overrides:
        - label: fast-datapath-for-rhel-8-x86_64-rpms
          override: enabled
        - label: ansible-2.9-for-rhel-8-x86_64-rpms
          override: enabled
        - label: satellite-tools-6.7-for-rhel-8-x86_64-rpms
          override: enabled
    auto_attach: False
...
