- name: setup virtualization box
  become: yes
  hosts:
    - boxes
  roles:
    - role: virthost
      vars:
        virthost_configure_bridge: yes
        virthost_satellite_register: yes
        virthost_imagelv_size: 500G
