apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-uidrange
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-uidrange
  template:
    metadata:
      labels:
        app: nginx-uidrange
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups:
          - 2000
          - 3000
      containers:
      - name: nginx-uidrange
        image: nginxinc/nginx-unprivileged:1.18
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          # runAsUser: 1001
        ports:
        - containerPort: 8080
