apiVersion: v1
kind: Service
metadata:
  name: nginx-80
  labels:
    openshift-example: "yes"
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
