- name: Install needed network manager libs
  package:
    name:
      - NetworkManager-libnm
      - nm-connection-editor
      - python3-libsemanage
      - python3-policycoreutils
    state: present

- name: configure bridge
  nmcli:
    type: bridge
    state: present
    ifname: bridge0
    conn_name: bridge0
