- name: Install needed network manager libs
  package:
    name:
      - NetworkManager-libnm
      - nm-connection-editor
      - python3-libsemanage
      - python3-policycoreutils
    state: present

- name: Configure bridge interface
  nmcli:
    type: bridge
    state: present
    ifname: bridge0
    conn_name: bridge0
    ip4: "{{ ansible_default_ipv4.address }}/24"
    gw4: "{{ ansible_default_ipv4.gateway }}"
    dns4: "{{ ansible_dns.nameservers }}"
    dns4_search: "{{ ansible_dns.search }}"

- name: Configure physcal interface as a bridge member
  nmcli:
    type: ethernet
    conn_name: "{{ virthost_interface }}-bridge0"
    ifname: "{{ virthost_interface }}"
    master: bridge0
    state: present
