- name: Check if we have a rootvg
  command: /sbin/vgs rootvg
  register: virthost_rootvg
  ignore_errors: True
  changed_when: False

- debug: var=virthost_rootvg

- name: Create mount point for libvirt images
  block:
  - name: Create a logical volume for virt images
    community.general.lvol:
      vg: rootvg
      lv: imagelv
      size: "{{ virthost_imagelv_size }}"

  - name: Create filesystem for virt images
    filesystem:
      fstype: xfs
      dev: /dev/rootvg/imagelv
      resizefs: yes

  - name: Mount virt image filesystem
    mount:
      path: /var/lib/libvirt/images
      src: /dev/rootvg/imagelv
      fstype: xfs
      state: mounted
  when: not virthost_rootvg.failed
