apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: sno-tq27v
  name: sno-tq27v-worker-aarch64-eu-central-1a
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: sno-tq27v
      machine.openshift.io/cluster-api-machineset: sno-tq27v-worker-eu-central-1a
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: sno-tq27v
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: sno-tq27v-worker-eu-central-1a
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/worker: ""
      providerSpec:
        value:
          ami:
            id: ami-03a26f8df1f590a17
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp3
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: sno-tq27v-worker-profile
          instanceType: c6g.large
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: eu-central-1a
            region: eu-central-1
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - sno-tq27v-worker-sg
          subnet:
            filters:
              - name: tag:Name
                values:
                  - sno-tq27v-private-eu-central-1a
          tags:
            - name: kubernetes.io/cluster/sno-tq27v
              value: owned
            - name: cluster
              value: sno
          userDataSecret:
            name: worker-user-data
