---
- name: Create OCP4 hosts
  gather_facts: no
  become: yes
  hosts:
    - localhost
  vars:
    satellite:
      host: https://satellite.lan.stderr.at
    lab:
      ssh_public_key: ""
      name: ocp
      network:
        type: bridge
        name: bridge0
      hosts:
        - name: bastion
          network: bridge0
          macaddr: "52:54:00:01:50:03"
          ipaddr: "10.0.0.180"
          disksize: 50G
          memory: 4096
          cpu: 2
          register: yes
          activationkey: "RHEL 8"
          image: rhel-8.2-update-2-x86_64-kvm.qcow2
          additional_disks:
            - name: bastion-vdb
              target: vdb
              size: 200G
        - name: bootstrap
          network: bridge0
          macaddr: "52:54:00:01:01:81"
          ipaddr: "10.0.0.181"
          disksize: 50G
          memory: 4096
          cpu: 2
          image: blank
        - name: master01
          network: bridge0
          macaddr: "52:54:00:01:01:82"
          ipaddr: "10.0.0.182"
          disksize: 120G
          memory: 12288
          cpu: 4
          image: blank
        - name: master02
          network: bridge0
          macaddr: "52:54:00:01:01:83"
          ipaddr: "10.0.0.183"
          disksize: 120G
          memory: 12288
          cpu: 4
          image: blank
        - name: master03
          network: bridge0
          macaddr: "52:54:00:01:01:84"
          ipaddr: "10.0.0.184"
          disksize: 120G
          memory: 12288
          cpu: 4
          image: blank
        - name: infra01
          network: bridge0
          macaddr: "52:54:00:01:01:85"
          ipaddr: "10.0.0.185"
          disksize: 120G
          memory: 8192
          cpu: 2
          image: blank
        - name: worker01
          network: bridge0
          macaddr: "52:54:00:01:01:88"
          ipaddr: "10.0.0.188"
          disksize: 120G
          memory: 8192
          cpu: 2
          image: blank

  roles:
    - lab

- name: Configure the bastion host
  hosts:
    - bastion
  roles:
    - role: vpn
      vars:
        vpn_configure_client: true
        vpn_server: playground
  post_tasks:
    - name: install required packages
      package:
        name:
        - git
        - ansible
        - lvm2
        state: present

    - name: Create a new primary partition
      parted:
        device: /dev/vdb
        number: 1
        state: present

    - name: create physical volume for lvm
      lvg:
        vg: nfsvg
        pvs: /dev/vdb1

    - name: create nfs volume group
      lvol:
        vg: nfsvg
        lv: nfslv

    - name: create nfs filesystem
      filesystem:
        type: xfs
        dev: /dev/nfsvg/nfslv

    - name: create mountpoint for nfs
      mount:
        path: /exports/nfs
        src: /dev/nfsvg/nfslv
        fstype: xfs
        state: mounted

    - name: create export entry for nfs
      lineinfile:
        path: /etc/exports
        regexp: '^/exports/nfs'
        line: "/exports/nfs    *(rw)"

    - name: Clone help node repo
      git:
        repo: https://github.com/tosmi/ocp4-helpernode
        dest: /root/ocp4-helpernode
