---
# This is an example of using nmstate nncp to configure a VLAN
#
# The VLAN interface bondvirt1.666 is also accessible from the host.
# That corresponding NAD for pods must NOT include the VLAN tag.
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  labels:
    app.kubernetes.io/instance: virt-network-sno-home
  name: brvirt1-policy
spec:
  nodeSelector:
    kubernetes.io/hostname: fractal.lan.stderr.at
  desiredState:
    interfaces:
    - bridge:
        options:
          stp:
            enabled: false
        port:
        - name: enp6s0
      description: Linux bridge on fractal with enp6s0 as a port
      ipv4:
        enabled: false
      name: brvirt1
      state: up
      type: linux-bridge

    # Does not work currently ARP only visible on brvirt and not on
    # the phy interface enp6s0
    - name: brvirt1.666
      type: vlan
      state: up
      ipv4:
        dhcp: false
        enabled: false
      vlan:
        base-iface: brvirt1
        id: 666
