apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  labels:
    app.kubernetes.io/instance: virt-network-sno-home
  name: brvirt1-policy
spec:
  nodeSelector:
    kubernetes.io/hostname: fractal.lan.stderr.at
  desiredState:
    interfaces:
    - bridge:
        options:
          stp:
            enabled: false
        port:
        - name: enp6s0
      description: Linux bridge on fractal with enp6s0 as a port
      ipv4:
        enabled: false
      name: brvirt1
      state: up
      type: linux-bridge
